sonar.projectKey=taxonomy
sonar.projectName=taxonomy
sonar.projectVersion=0.2.0

sonar.sources=app,components,lib,types,hooks,actions,middleware.ts,env.mjs,contentlayer.config.js,next.config.mjs

sonar.tests=tests
sonar.test.inclusions=**/*.spec.ts

sonar.exclusions=**/node_modules/**,**/.next/**,**/build/**,**/.contentlayer/**,**/playwright-report/**,**/test-results/**,**/.scannerwork/**,presentation/**,docs/**

sonar.sourceEncoding=UTF-8
